"""
Django settings for BrainworX project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import django_heroku
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i2n1gw1u+hjihh)y*y70p6^8&!$#y3_l1(x^(1!8(sf!sn%i(f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

HOST = 'http://127.0.0.1:8000'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'videos',
    'accounts',
    'user',
    'pp',
    'chat',
    'payment',

    #3rd party apps
    #'rest_framework',
    #'corsheaders',
    'crispy_forms',
    'import_export',
    'mathfilters',
    'djangorave',

]

#not recommended in production instead just add those domains that need to be whitelisted.
#CORS_ORIGIN_ALLOW_ALL = True


MIDDLEWARE = [
    #'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BrainworX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BrainworX.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.sqlite3',
   #     'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}

#DATABASES = {
    #'default': {
     #   'ENGINE': 'django.db.backends.mysql',
      #  'NAME': "BrainworX",
       # 'USER': "root",
        #'PASSWORD': "Root2580",
        #'HOST': "localhost",
        #'PORT': '3306'
    #}
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'root2580',
        'HOST':'127.0.0.1',
        'POST':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Harare'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL='/media/'

STATIC_ROOT=BASE_DIR/'static_root'
MEDIA_ROOT=BASE_DIR/'media'

STATICFILES_DIRS=[
    BASE_DIR/'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#password reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'novofan58@gmail.com'
EMAIL_HOST_PASSWORD = 'Root2580'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


#email activate
DEFAULT_FROM_EMAIL = 'novofan58@gmail.com'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

X_FRAME_OPTIONS = 'SAMEORIGIN'

#payment
WILDLIFE_LOGO = 'https://res.cloudinary.com/fullstackmafia/image/upload/v1574344653/green-forest-trees.jpg.860x0_q70_crop-scale_n8k6hs.jpg'

RAVE_PRODUCTION_PUBLIC_KEY = ""
RAVE_PRODUCTION_SECRET_KEY = ""
RAVE_SANDBOX_PUBLIC_KEY = "FLWPUBK_TEST-5001dde5aef91226f43641cb6d065c53-X"
RAVE_SANDBOX_SECRET_KEY = "FLWSECK_TEST-68b9018cf3bd66e49ab2aad1ba835da6-X"
RAVE_SANDBOX = True

JAZZMIN_SETTINGS={
    "site_title": "BWX Admin",
    "site_header": "BWX Admin",
    "order_with_respect_to": ["auth", "payment.SubPlan","payment.SubPlanFeature", "payment.Subscriber", "payment.Subscription", "payment.FlwPlanModel", "pp.Book", "videos.videos"],
}

# Activate Django-Heroku.
django_heroku.settings(locals())